version: "3"
services:
  web:
    build: .
    ports:
      - "8545:8545"
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./app/test:/app/test
      - ./app/tasks:/app/tasks
      - ./app/src:/app/src
      - ./app/scripts:/app/scripts
      - ./app/contracts:/app/contracts
      - ./app/frontend:/app/frontend  
      - ./app/package.json:/app/package.json
      - ./app/package-lock.json:/app/package-lock.json
      - ./app/hardhat.config:/app/hardhat.config
    environment:
      - WATCHPACK_POLLING=true
